# Generated by Django 5.0.7 on 2024-10-01 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='users/profile_pictures'),
            preserve_default=False,
        ),
    ]
