# Generated by Django 5.0.7 on 2024-08-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='is_active',
        ),
    ]
